version: '3.8'

services:
  app:
    image: ${DOCKER_IMAGE}
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE
      - SPRING_DATASOURCE_URL
      - SPRING_DATASOURCE_USERNAME
      - SPRING_DATASOURCE_PASSWORD
      - API_SECURITY_TOKEN_SECRET
    restart: always
    networks:
      - firewatch-network

  prometheus:
    image: prom/prometheus
    volumes:
      - ./monitoring/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    restart: always
    networks:
      - firewatch-network

  grafana:
    image: grafana/grafana
    env_file:
      - .env.production
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_PASSWORD}
    volumes:
      - grafana-data:/var/lib/grafana
      - ./monitoring/grafana/firewatch-dashboard.json:/etc/grafana/provisioning/dashboards/firewatch-dashboard.json
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
    restart: always
    networks:
      - firewatch-network

networks:
  firewatch-network:
    driver: bridge

volumes:
  grafana-data: