site_name: FireWatch03 - Documentação DevOps
theme:
  name: material
  language: pt-BR
  features:
    - navigation.tabs
    - navigation.sections
    - content.tabs
    - content.code.annotate
    - toc.integrate
  palette:
    - scheme: default
      primary: deep purple
      accent: teal
    - scheme: slate
      primary: black
      accent: lime
  icon:
    repo: fontawesome/brands/github

plugins:
  - search
  - mermaid2
  - macros
  - pdf-export
  - with-pdf:
      cover_subtitle: "Sistema de Monitoramento para Cidades Inteligentes"
      output_path: pdf/documentacao-firewatch03.pdf
  - awesome-pages

markdown_extensions:
  - admonition
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.details
  - pymdownx.tabbed
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - attr_list
  - md_in_html
  - tables

nav:
  - Início: index.md
  - Pipeline CI/CD: pipeline.md
  - Containerização e Orquestração: containerizacao.md
  - Evidências e Execução: evidencias.md
