site_name: FireWatch03 - Documentação DevOps
theme:
  name: material
  language: pt-BR
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - search.suggest
    - search.highlight
    - content.code.copy
  palette:
    primary: red
    accent: orange

plugins:
  - search
  - mermaid2
  - pdf-export
  - macros
  - awesome-pages
  - with-pdf:
      cover_subtitle: "Sistema de Monitoramento para Cidades Inteligentes"
      output_path: pdf/documentacao-firewatch03.pdf

markdown_extensions:
  - admonition
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.details
  - pymdownx.tabbed
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - attr_list
  - md_in_html
  - tables

nav:
  - Início: index.md
  - Sobre o Projeto: projeto.md
  - Pipeline CI/CD: pipeline.md
  - Containerização e Orquestração: containerizacao.md
  - Evidências e Execução: evidencias.md